services:
  postgres:
    image: postgres:latest
    container_name: postgresuser
    restart: unless-stopped

    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbnext

    ports:
      - "5464:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d dbnext"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: backend
    restart: unless-stopped

    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://dbuser:password@postgres:5462/dbnext?schema=public

    ports:
      - "5000:5000"

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: